### ISSUE TITLE
Keycloak 22 not compatible

### ISSUE THREAD

**Issue by belfhi** [privacyidea/keycloak-provider#143]
Keycloak 22 produces the following error:

```
2023-07-13 11:46:04,122 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-620) Uncaught server error: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at org.privacyidea.Endpoint.<init>(Endpoint.java:74)
	at org.privacyidea.PrivacyIDEA.<init>(PrivacyIDEA.java:76)
	at org.privacyidea.PrivacyIDEA.<init>(PrivacyIDEA.java:57)
	at org.privacyidea.PrivacyIDEA$Builder.build(PrivacyIDEA.java:670)
	at org.privacyidea.authenticator.PrivacyIDEAAuthenticator.createInstance(PrivacyIDEAAuthenticator.java:107)
	at org.privacyidea.authenticator.PrivacyIDEAAuthenticator.authenticate(PrivacyIDEAAuthenticator.java:139)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:445)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:249)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:380)
	at org.keycloak.authentication.DefaultAuthenticationFlow.continueAuthenticationAfterSuccessfulAction(DefaultAuthenticationFlow.java:181)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:157)
	at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:986)
	at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:378)
	at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:349)
	at org.keycloak.services.resources.LoginActionsService.authenticateInternal(LoginActionsService.java:341)
	at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:322)
	at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:406)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:174)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:131)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:33)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:84)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:44)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	at io.vertx.ext.web.impl.RoutingContextWrapper.next(RoutingContextWrapper.java:200)
	at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

from the Release notes:
>Removing thirdparty dependencies
The removal of openshift-integration allows us to remove few thirdparty dependencies from Keycloak distribution. This includes openshift-rest-client, okio-jvm, okhttp, commons-lang, commons-compress, jboss-dmr and kotlin-stdlib. This means that if you use any of these libraries as dependencies of your own providers deployed to Keycloak server, you may also need to copy those jar files explicitly to the Keycloak distribution providers directory as well.

It seems the dependencies need to be added to the privacyidea plugin.

**Comment by nilsbehlen** [comment]
thanks for the info, i will look into it.

**Comment by nilsbehlen** [comment]
kc22 is unusable currently, waiting for this:
https://github.com/keycloak/keycloak/pull/21662

**Comment by gryffus** [comment]
Still happens in 22.0.1 ( https://github.com/keycloak/keycloak/pull/21662 should be fixed in 22.0.1 )

**Comment by nilsbehlen** [comment]
I will see if i can work with 22.0.1 then to fix this

**Comment by nilsbehlen** [comment]
I fixed it, but it will take some more time to make a official release, either as a fix of 1.2.0 or new 1.3.0.
If you want, you can check this, if it works for you:
[PrivacyIDEA-Provider-v1.2.0.KC22.jar.zip](https://github.com/privacyidea/keycloak-provider/files/12160478/PrivacyIDEA-Provider-v1.2.0.KC22.jar.zip)

**Comment by belfhi** [comment]
Ah danke ich hatte es in meinem Fork auch hinbekommen aber war noch nicht dazu gekommen einen PR zu erstellen 🙈

**Comment by nilsbehlen** [comment]
Kein Problem, ist aber nicht mehr mit 21 kompatibel und mit 20 schon garnicht, deshalb wird der offizielle release noch ein bisschen dauern.

**Comment by belfhi** [comment]
why does a new version _have_ to be backwards compatible? If there is a supported Keycloak Version matrix that should be enough, no? Thanks for the `.jar` in the meantime :)

**Comment by gryffus** [comment]
I can confirm correctly working with KC 22.0.1 and PA 3.8.1.
